package objects;
// Generated 23-Jan-2017 00:45:44 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PatientSymptomsId generated by hbm2java
 */
@Embeddable
public class PatientSymptomsId  implements java.io.Serializable {


     private int patientSymptomsId;
     private int symptomsId;
     private int patientId;

    public PatientSymptomsId() {
    }

    public PatientSymptomsId(int patientSymptomsId, int symptomsId, int patientId) {
       this.patientSymptomsId = patientSymptomsId;
       this.symptomsId = symptomsId;
       this.patientId = patientId;
    }
   


    @Column(name="patient_symptoms_Id", nullable=false)
    public int getPatientSymptomsId() {
        return this.patientSymptomsId;
    }
    
    public void setPatientSymptomsId(int patientSymptomsId) {
        this.patientSymptomsId = patientSymptomsId;
    }


    @Column(name="symptoms_Id", nullable=false)
    public int getSymptomsId() {
        return this.symptomsId;
    }
    
    public void setSymptomsId(int symptomsId) {
        this.symptomsId = symptomsId;
    }


    @Column(name="patient_Id", nullable=false)
    public int getPatientId() {
        return this.patientId;
    }
    
    public void setPatientId(int patientId) {
        this.patientId = patientId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PatientSymptomsId) ) return false;
		 PatientSymptomsId castOther = ( PatientSymptomsId ) other; 
         
		 return (this.getPatientSymptomsId()==castOther.getPatientSymptomsId())
 && (this.getSymptomsId()==castOther.getSymptomsId())
 && (this.getPatientId()==castOther.getPatientId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPatientSymptomsId();
         result = 37 * result + this.getSymptomsId();
         result = 37 * result + this.getPatientId();
         return result;
   }   


}


