package objects;
// Generated 23-Jan-2017 00:45:44 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PatientSymptoms generated by hbm2java
 */
@Entity
@Table(name = "patient_symptoms")
public class PatientSymptoms {

     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)
     
     @Column(name = "Id")
     private int id;
     @Column (name = "Patient_ID")
     private int patient_id;
     @Column(name = "Date")
     private String date;
     @Column(name = "Temperature")
     private Integer temperature;
     @Column(name = "Vomiting")
     private String vomiting;
     @Column(name = "Diarrhoea")
     private String diarrhoea;
     @Column(name = "Rash")
     private String rash;
     @Column(name = "Chestpain")
     private String chestpain;
     @Column(name = "Nausea")
     private String nausea;
     @Column(name = "Haemorrhaging")
     private String haemorrhaging;
     @Column(name = "Endemic_country_visited")
     private String endemic_country_visited;
     @Column(name = "Burns")
     private String burns;
     @Column(name = "Movement_of_limbs")
     private String movement_of_limbs;
     @Column(name = "Constipation")
     private String constipation;
     @Column(name = "Breathing_problems")
     private String breathing_problems;
     @Column(name = "Pain")
     private String pain;
     @Column(name = "Headache")
     private String headache;
     

    public PatientSymptoms() {
    }

    public PatientSymptoms(String Date, Integer temperature, String vomiting, String diarrhoea, String rash, String chestpain, String nausea, String haemorrhaging, String endemic_country_visited, String burns, String movement_of_limbs, String constipation, String breathing_problems, String pain, String headache) {
       this.date = date;
       this.temperature = temperature;
       this.vomiting = vomiting;
       this.diarrhoea = diarrhoea;
       this.rash = rash;
       this.chestpain = chestpain;
       this.nausea = nausea;
       this.haemorrhaging = haemorrhaging;
       this.endemic_country_visited = endemic_country_visited;
       this.burns = burns;
       this.movement_of_limbs = movement_of_limbs;
       this.constipation = constipation;
       this.breathing_problems = breathing_problems;
       this.pain = pain;
       this.headache = headache;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    
    
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }
   
    
    public Integer getTemperature() {
        return this.temperature;
    }
    
    public void setTemperature(Integer temperature) {
        this.temperature = temperature;
    }

    
    public String getVomiting() {
        return this.vomiting;
    }
    
    public void setVomiting(String vomiting) {
        this.vomiting = vomiting;
    }

    
    public String getDiarrhoea() {
        return this.diarrhoea;
    }
    
    public void setDiarrhoea(String diarrhoea) {
        this.diarrhoea = diarrhoea;
    }

    
    public String getRash() {
        return this.rash;
    }
    
    public void setRash(String rash) {
        this.rash = rash;
    }

    
    public String getChestpain() {
        return this.chestpain;
    }
    
    public void setChestpain(String chestpain) {
        this.chestpain = chestpain;
    }

    
    public String getNausea() {
        return this.nausea;
    }
    
    public void setNausea(String nausea) {
        this.nausea = nausea;
    }

    
    public String getHaemorrhaging() {
        return this.haemorrhaging;
    }
    
    public void setHaemorrhaging(String haemorrhaging) {
        this.haemorrhaging = haemorrhaging;
    }

    
    public String getEndemicCountryVisited() {
        return this.endemic_country_visited;
    }
    
    public void setEndemicCountryVisited(String endemic_country_visited) {
        this.endemic_country_visited = endemic_country_visited;
    }

    
    public String getBurns() {
        return this.burns;
    }
    
    public void setBurns(String burns) {
        this.burns = burns;
    }

    
    public String getMovement_of_limbs() {
        return this.movement_of_limbs;
    }
    
    public void setMovement_of_limbs(String movement_of_limbs) {
        this.movement_of_limbs = movement_of_limbs;
    }

    
    public String getConstipation() {
        return this.constipation;
    }
    
    public void setConstipation(String constipation) {
        this.constipation = constipation;
    }

    
    public String getBreathingProblems() {
        return this.breathing_problems;
    }
    
    public void setBreathingProblems(String breathing_problems) {
        this.breathing_problems = breathing_problems;
    }

    
    public String getPain() {
        return this.pain;
    }
    
    public void setPain(String pain) {
        this.pain = pain;
    }

    public String getHeadache() {
        return headache;
    }

    public void setHeadache(String headache) {
        this.headache = headache;
    }






}


